### ISSUE TITLE
Exception: Attribute has duplicate labels

### ISSUE THREAD

**Issue by vhazali** [secure-software-engineering/SuSi#10]
![image](https://cloud.githubusercontent.com/assets/8543547/20171052/f2d6874c-a769-11e6-8be0-2887fdc734c2.png)

I'm trying to use SuSi to generate list of sources and sinks for FlowDroid, for some versions of android platforms. 

For this particular screenshot, I was running SuSi with android-8 android.jar, obtained from the [GitHub page](https://github.com/Sable/android-platforms) mentioned in the `README`.

The same problem was encountered with android-15 android.jar

I've made sure to download the nightly build for soot (`soot-trunk.jar`, `soot-infoflow.jar` and `soot-infoflow-android.jar`) based on the instructions [here](https://github.com/secure-software-engineering/soot-infoflow-android/wiki).

SuSi was built using the Ant build `build.xml` provided in the repo, and for the learning file input I used the provided `permissionMethodWithLabel.pscout` 

Not sure if this is due to a mistake in setting up on my part or is there something wrong with the repo. Could anyone please help clarify?

**Comment by suguofei** [comment]
Encountered the same problem, there is no solution
Have you resolved?

**Comment by vhazali** [comment]
We were using it for a school assignment. So what we did was to modify the code slightly. Basically we ensure that the `Attribute` doesn't contain the ID before adding it in. So for our purposes it was sufficient, not sure(probably did) if we reduced the accuracy of SuSi by doing so. You can see the changes by my friend in his fork [here](https://github.com/lejolly/SuSi)
