### ISSUE TITLE
Any results on recent Android API versions ?

### ISSUE THREAD

**Issue by louison** [secure-software-engineering/SuSi#11]
Hi all, 

Thanks for all the work on SuSi and FlowDroid by extension.
I was wondering if it is meaningful to run SuSi on recent Android versions ?
If so, has it been done already ? 

Thank you in advance

**Comment by ezamorab** [comment]
Hi @LouisonGitzinger 
Did you find anything useful? I'm looking for a list of sources and sinks for recent Android versions, better if it's already ready, since I'm not able to run SuSi....

Thanks a lot!

**Comment by louison** [comment]
hi @ezamorab, 

I do not have a better solution than SuSi for sources and sinks. I'm currently using this dataset for my work. Actually it still works pretty well on newer Android versions.
I use [these files](https://github.com/secure-software-engineering/SuSi/tree/develop/SourceSinkLists/Android%204.2/SourcesSinks).

 You can also have a look to the [Axplorer](http://axplorer.org/) project. It is a research team that extracted `permission protected` method calls in the Android framework.

Hope it helps,
