### ISSUE TITLE
Building the package code problem

### ISSUE THREAD

**Issue by AmrAshraf** [secure-software-engineering/SuSi#13]
I am trying to build the project but it gives me,
Can't resolve the following ones

```
 import soot.jimple.infoflow.android.data.AndroidMethod.CATEGORY;
 import soot.jimple.infoflow.android.data.AndroidMethodCategoryComparator;
```

I am using soot-infoflow-android 2.5.1 the newest build of dependent soot libraries.
I even open its source code and i can't found `CATEGORY` and `AndroidMethodCategoryComparator `in the `AndroidMethod `class.

**Comment by AmrAshraf** [comment]
Solved by getting flowdroid version 2 instead of 2.5

**Comment by StevenArzt** [comment]
There has been some refactoring. The CATEGORY enumeration is now part of "soot.jimple.infoflow.android.data.CategoryDefinition".
