### ISSUE TITLE
issues related to SuSi

### ISSUE THREAD

**Issue by kidccit** [secure-software-engineering/SuSi#6]
Hi all,
I am doing a project related to android application and I am using SuSi to identifying the sources and sinks of an android application. However I've got some doubt regarding to the input of SuSi.
1. The input parameters to run SuSi (run [main] function in class SourceSinkFinder) are :
   <android jar file path> <file SourcesAndSinks.txt> <output file>
   I get the file [SourcesAndSinks.txt] from project [soot_infoflow_android], and it seems like the file is already out updated. Where or how I can get the newest version of this file?
2. In folder of the project SuSi, i see a folder namely SourceSinkLists/Android 4.2/SourcesSinks that contains two files:
   - Output_CatSinks_v0_9.txt
   - Output_CatSources_v0_9.txt

Are both of them the sources and sinks APIs of android APIs version 4.2? 
If yes, how can I get those files for Android 5.1 API level 22?
If no, how can I get or create a list of sources and sinks APIs of android APIs?
1. When I input those parameters to SuSi 
   ".\android.jar" <.\SourcesAndSinks.txt> <.\Output.txt> and then run. The program caused an exception below:

Something went all wonky: java.lang.RuntimeException: Could not find NO_CATEGORY index
java.lang.RuntimeException: Could not find NO_CATEGORY index
    at de.ecspride.sourcesinkfinder.SourceSinkFinder.analyzeCategories(SourceSinkFinder.java:673)
    at de.ecspride.sourcesinkfinder.SourceSinkFinder.run(SourceSinkFinder.java:174)
    at de.ecspride.sourcesinkfinder.SourceSinkFinder.main(SourceSinkFinder.java:135)

Could you please tell me the reason of the exception and how to fix it.
I really appreciate for your help.

Thanks and Regards.
Nero N

**Comment by StevenArzt** [comment]
For running SuSi, you need to specify the input file containing the hand-annotated training set. On this set, SuSi will then train both classifiers (the first one for distinguishing the classes "source", "sink", and "neither", and the second one for identifying the category to which an identified source or sink belongs). Our version of this file is called "permissionMethodWithLabel.pscout" and is available in the SuSi repository. You can either use it directly or extend or modify it to meet your needs.

The SourcesAndSinks.txt file shipped with FlowDroid is not an input to SuSi. It is the other way round: You can use the files generated by SuSi as source and sink definition files for FlowDroid. The goal of SuSi is to generate the source and sink definitions that can then be used by tools such as FlowDroid.

The files in the "Android 4.2" folder are the SuSi outputs for Android version 4.2, API 22, that's right.

The exception you received is most likely a consequence of the wrong input file.

**Comment by kidccit** [comment]
Thank you so much for your reply StevenArzt.
I have tried to use the file [permissionMethodWithLabel.pscout] as you mentioned for the input of SuSi. Indeed, I used the inputs below for running SuSi
".\eclipse-java-kepler-SR1-win32-x86_64\sdk\platforms\android-22" ".\SuSi-develop\permissionMethodWithLable.pscout" "C:\SuSi.ouput"

when SuSi is running , I have seen that all of classes defined in the file [permissionMethodWithLabel.pscout] are phantom classes and then it shows the error (in red color) that such phantom classes are not found.
i.e Class com.google.common.io.ByteStreams not found

It also throws some other exceptions such as:

Something went all wonky: java.lang.IllegalArgumentException: Can't have more folds than instances!
java.lang.IllegalArgumentException: Can't have more folds than instances!
    at weka.core.Instances.trainCV(Instances.java:1409)
    at weka.core.Instances.trainCV(Instances.java:1444)
    at weka.classifiers.Evaluation.crossValidateModel(Evaluation.java:474)
    at de.ecspride.sourcesinkfinder.SourceSinkFinder.analyzeSourceSinkWeka(SourceSinkFinder.java:531)

OR

Something went all wonky: java.lang.RuntimeException: Could not find NO_CATEGORY index
java.lang.RuntimeException: Could not find NO_CATEGORY index
    at de.ecspride.sourcesinkfinder.SourceSinkFinder.analyzeCategories(SourceSinkFinder.java:675)

AND so on.

And after all, no result of sources or sinks is generated. Can you tell me what wrong I did?

Thank for your suppport

**Comment by StevenArzt** [comment]
The two error messages can both occur if SuSi was unable to load any methods from your platform JAR file. Note that SuSi needs a full file path on the command line, not just a directory. You need to precisely point SuSi to the JAR file. Furthermore, you need a full JAR file containing an actual implementation of the Android framework. The stubbed platform JAR files shipped with the Android SDK won't work as they do not contain any actual implementations. For older Android versions, there are some full JARs available on Github: https://github.com/Sable/android-platforms. For newer Android versions, you will have to build those JARs on your own.

**Comment by kidccit** [comment]
In deed, I specified exactly a full path of jar file in Eclipse for running Susi. Just because i think it is simpler for reader to follow the topic, I shortened the path. 
Now I know why the error occurred. I have used the android version 22. But what do you mean "build those JARs on my own"? 
Because I'm starting investigating how Susi can evolve when Android APIs change everytime.

Thank you so much for your answer Steven.

**Comment by fuyunguagua** [comment]
谢谢你俩！

**Comment by StevenArzt** [comment]
The repository here on Github only contains the JAR files for some versions of Android. If you need a JAR file for another version of Android, you need to manually extract it from a device or emulator. It's perfectly possible, but it's quite some work. There are tutorials on the Internet, e.g., http://stackoverflow.com/questions/10986864/where-can-i-find-the-android-source-jars.

**Comment by Arslan91** [comment]
Hi Steven,

Could you explain how to build platform jars on our own. I'm really confused about this line.

Thanks.

**Comment by sunxiaobiu** [comment]
I run SuSi successfully on the latest Android version 30 by using the jar from [https://github.com/Reginer/aosp-android-jar](url). In case someone needs it

**Comment by marshalwahlexyz001** [comment]
> 

Hi, I am having trouble building the SuSi framework as there is no installation guide. Please can you give instructions on how to successfully build SuSi

**Comment by StevenArzt** [comment]
Please do not comment on old issues. If there is a new problem, open your own issue. This one has been closed many years ago.
