### ISSUE TITLE
About lib

### ISSUE THREAD

**Issue by fm-chen** [secure-software-engineering/SuSi#7]
Hi guys,
I notice that your project include soot-trunk.jar, soot-infoflow.jar and soot-infoflow-android.jar. but I cannot find it in lib. So, did I need these three jars?

**Comment by fm-chen** [comment]
Description Resource    Path    Location    Type
Project 'SourceSinkFinder' is missing required Java project: 'soot-infoflow-android'    SourceSinkFinder        Build path  Build Path Problem
Project 'SourceSinkFinder' is missing required Java project: 'soot-infoflow'    SourceSinkFinder        Build path  Build Path Problem
Project 'SourceSinkFinder' is missing required Java project: 'soot' SourceSinkFinder        Build path  Build Path Problem
The project cannot be built until build path errors are resolved    SourceSinkFinder        Unknown Java Problem

**Comment by srasthofer** [comment]
Hi,
You can find all information here: https://github.com/secure-software-engineering/soot-infoflow-android/wiki

However, I would recommend checking out the source of those projects instead of the nightly builds. Also this information is provided on that website.

Regards,
Siegfried
