### ISSUE TITLE
About FlowDroid.

### ISSUE THREAD

**Issue by fm-chen** [secure-software-engineering/SuSi#8]
Thanks for your time, and I feel really excited for your reply of my last question. As your recommend, I download and follow the step that describe in https://github.com/secure-software-engineering/soot-infoflow-android/wiki  to build the whole project. But there still a bug occurs when I am trying to import "soot-develop" into eclipse. The error that "Parser cannot be resolved to a type" happened in File whose path is /soot/src/soot/jimple/parser and resource is JimpleAST.java and Parse.java.
I am rookie and really interest in your fabulous project. But your project is too complex for me, I cannot fix this bug by myself. So, I will appreciate it if you can help me~ Thanks again.

**Comment by StevenArzt** [comment]
Have you imported Soot as an existing project into Eclipse? You should then automatically get a working build configuration. Your error message looks like a missing build folder.

**Comment by fm-chen** [comment]
Yes，I imported Soot as an existing project into eclipse. The error occurs in: 
Parser p = 
                new Parser(new Lexer(
                      new PushbackReader(new EscapedReader(new BufferedReader(
                              new InputStreamReader(istream))), 1024)));  
This Parser cannot be resolved to a type.    Should I import Parser into JimpleAST.java and Parse.java?  I am trying to import Parser from package generated.jastadd.beaver. but It does not work.
Or, maybe my "soot-develop" lack some folder? I am also trying to download again but this bug still exist . Is there any other places that I can download the "soot-develop" that I can import and finally run the FlowDroid?

Another question: I notice that when I import soot-develop into eclipse. In soot project, the package "generated/jastadd" above the package "src". But generally we set package "src" above all package. Do I have to adjust the order?

My mother language is not english, So, I do not know whether you can understand my question, anyway, Thank you very much~

**Comment by ericbodden** [comment]
Hi all.

I have known this problem to happen with special versions of Eclipse. It’s due to a bug in the Eclipse compiler, actually. Which version are you using? And could you try a different one?

Cheers,
Eric

**Comment by fm-chen** [comment]
@ericbodden   Oh, really? my version of eclipse is Luna Release (4.4.0). Do you know a safe version to run this project? Thank you ~ that's a big help!

**Comment by ericbodden** [comment]
> @ericbodden Oh, really? my version of eclipse is Luna Release (4.4.0). Do you know a safe version to run this project? Thank you ~ that's a big help!

I am not sure this bug was ever fixed. I think I was only able to compile this part of Soot on older Eclipse builds (like 3.7), not newer ones. I think the problem relates to some code in the “generated” folder in Soot. IIRC then the trick is to not build this code in Eclipse but instead link the Soot binaries that javac generates using the build scripts.

Cheers,
Eric
